blank_issues_enabled: true
# contact_links:
#   - name: Sample Support info
#     url: https://example.com/
#     about: Please rewrite if
#   - name: Sample Support info
#     url: https://example.com/
#     about: Please rewrite if
